from typing import Any, TypeVar

from networkx import Graph

T = TypeVar("T", bound=Graph)


def union(G, H, rename=..., name: Any | None = ...): ...
def disjoint_union(G: T, H: T) -> T: ...
def intersection(G: T, H: T) -> T: ...
def difference(G: T, H: T) -> T: ...
def symmetric_difference(G: T, H: T) -> T: ...
def compose(G, H): ...
def full_join(G, H, rename=...): ...
