from collections.abc import Generator
from typing import Any, List, Tuple


def cycle_basis(G, root: Any | None = ...): ...
def simple_cycles(G) -> Generator[Any, None, None]: ...
def recursive_simple_cycles(G): ...
def find_cycle(G, source: Any | None = ..., orientation: Any | None = ...) -> List[Tuple[Any, Any]]: ...
def minimum_cycle_basis(G, weight: Any | None = ...): ...
